### ISSUE TITLE
`console_in: !fd 3` triggers YAML parse error

### ISSUE THREAD

**Issue by mcandre** [NuxiNL/cloudabi-utils#7]
I am trying to wedge stdin as a file descriptor, so that my CloudABI program an act as a REPL. Am I using argdata / YAML syntax correctly?

# Source

https://github.com/mcandre/tonixxx/tree/issue-115/examples/fewer

# Configuration

```console
$ cat cloudabi.yml 
%TAG ! tag:nuxi.nl,2015:cloudabi/
---
console_out: !fd stdout
console_err: !fd stderr
console_in: !fd 3
file: !file
    path: README.md
```

# Trace

```console
$ cloudabi-run bin/fewer <cloudabi.yml 3</dev/stdin
yaml-cpp: error at line 5, column 13: XXX!
```

**Comment by mcandre** [comment]
@EdSchouten Thank you, Ed!

When can we expect a new release with this fix in the Debian repository?

**Comment by EdSchouten** [comment]
This only affects code outside of CloudABI executables. In other words, reinstalling the latest version of cloudabi-utils + yaml2argdata should be sufficient. I cut new releases the other day. Enjoy!
